# Generated by Django 6.0 on 2025-12-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password_admin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_usuario',
            field=models.CharField(max_length=255),
        ),
    ]
